services:

bookscan:
    build: .
    container_name: bookscan
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./databases:/app/databases
      - ./static:/app/static

    restart: unless-stopped